import SignInForm from "@/components/SignInForm"
import { Metadata } from "next"

const metadata: Metadata = {
    title: "    Log-In | MYSHOPBD",
    description: "Generated by create next app",

}

const SignIn = () => {

    return (
        <SignInForm />

    )
}

export default SignIn